spring:
  datasource:
    url: "jdbc:sqlite:///Users/asherwin/repos/github/httpinator/httpinator.db"
  flyway:
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    cleanDisabled: false
